### ISSUE TITLE
MGBox doesn't set border view.

### ISSUE THREAD

**Issue by ALychkovsky** [sobri909/MGBoxKit#140]
Hello! I want to set custom view at the object MGBox.
MGLine * line = ...;
UIView *separateView = ...;
[line setBottomBorder:separateView];  <- Doesn't work!

But setBottomBorderColor is working well.

Can you help me?

**Comment by sobri909** [comment]
Yeah the border views can't be replaced. They're auto generated. You'd be better to just add your custom border view as a plain subview.

Though given that it's an MGLine, be aware that you should set your view's tag to -2 or below, to avoid MGLine's layout method discarding it due to it being a subview outside its managed containers (left/middle/rightItems).

**Comment by ALychkovsky** [comment]
Hi, sobri909!

This code resolved me problem: 
[line.bottomBorder addSubview:separateView];
[line setBottomBorderColor:[UIColor lightTextColor]];

I hope that it will be right. ;)

**Comment by sobri909** [comment]
Sures. Sounds plausible.
